# fly.toml app configuration file generated for cune-herbarium on 2025-01-27T11:07:11-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cune-herbarium'
primary_region = 'den'
console_command = '/code/manage.py shell'

[build]

[deploy]
release_command = 'python manage.py migrate --noinput'

[env]
AWS_REQUEST_CHECKSUM_CALCULATION = 'WHEN_REQUIRED'
AWS_RESPONSE_CHECKSUM_VALIDATION = 'WHEN_REQUIRED'
DEBUG = 'f'
PORT = '8000'
STATICFILES_BACKEND = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STORAGE_BACKEND = 'storages.backends.s3.S3Storage'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[statics]]
guest_path = '/code/static'
url_prefix = '/static/'
