# Generated by Django 5.1.5 on 2025-01-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=256, verbose_name='genus')),
                ('species', models.CharField(max_length=256, verbose_name='species')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('common_name', models.CharField(max_length=256, verbose_name='common_name')),
                ('year', models.CharField(max_length=256, verbose_name='year')),
                ('collector', models.CharField(max_length=256, verbose_name='collector')),
                ('location', models.CharField(max_length=256, verbose_name='location')),
                ('cabinet', models.CharField(max_length=256, verbose_name='cabinet')),
                ('drawer', models.CharField(max_length=256, verbose_name='drawer')),
                ('extra_info', models.CharField(max_length=256, verbose_name='extra_info')),
            ],
        ),
    ]
