# Generated by Django 5.1.5 on 2025-04-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_herbarium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='ramarks',
            field=models.TextField(blank=True, null=True, verbose_name='ramarks'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='collector',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='collector'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='common_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='common_name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='extra_info',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='extra_info'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='genus',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='genus'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='species'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='year',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='year'),
        ),
    ]
