# Generated by Django 5.1.5 on 2025-04-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_herbarium', '0002_plant_ramarks_alter_plant_collector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.AddField(
            model_name='plant',
            name='specimen_image',
            field=models.ImageField(blank=True, null=True, upload_to='specimen_img/'),
        ),
    ]
