# Generated by Django 5.1.5 on 2025-04-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_herbarium', '0003_remove_plant_image_plant_specimen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='info_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='info_card_img/'),
        ),
    ]
